# -*- coding: utf-8 -*-
"""BIOS 635 Midterm Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrhfD_0Z_r0IC2l2rP-NYQKgQZicwWZn
"""

#import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#ML tools
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, roc_curve

#models to test
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgb

#warnings
import warnings
warnings.filterwarnings("ignore")

#load training dataset (sample rows)

df = pd.read_csv("train.csv", nrows=150000)

#check dataset size
print("Dataset shape:", df.shape)

df.head(10)

#show distribution of prediction target
print("Adverse outcome distribution:")
print(df["adverse_outcome"].value_counts(normalize=True))

print("\nReadmission distribution:")
print(df["readmission_30d"].value_counts(normalize=True))

df["adverse_outcome"].value_counts().plot(kind="bar")
plt.title("Distribution of Adverse Outcomes")
plt.xlabel("Outcome (0 = no event, 1 = ICU/death)")
plt.ylabel("Number of Patients")
plt.show()

"""Around 41% of patients experience ICU admission or death"""

#identifying features w/missing values
missing = df.isna().sum().sort_values(ascending=False)
print("Top columns with missing values:")
print(missing.head(15))

"""High missingness in labs like troponin and BNP because doctors only order these tests if they see something concerning and think its necessary."""

#remove leakage column
if "disposition" in df.columns:
    df = df.drop(columns=["disposition"])

#remove IDs
df = df.drop(columns=["encounter_id"])

#convert categorical
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype("category")

#define prediction target
y_adverse = df["adverse_outcome"]
y_readmit = df["readmission_30d"]

#remove both target columns from predictors
X = df.drop(columns=["adverse_outcome", "readmission_30d"])

#create missingness indicators - b/c if n/a then the doctor didn't suspect anything bad to need to order test
lab_cols = [
    "troponin_i_ngml",
    "bnp_pgl",
    "d_dimer_mgfl",
    "lactate_mmoll",
    "lipase_ul",
    "procalcitonin_ngl",
    "albumin_gdl"
]

for col in lab_cols:
    if col in X.columns:
        X[col + "_missing"] = X[col].isna().astype(int)

"""Useful because for example if troponin is missing, it means the doctor didn't suspect heart attack so he didn't order test."""

#convert categorical
X = pd.get_dummies(X, drop_first=True)
print("Feaeture matrix shape:", X.shape)

#using median imputation to fill missing values
imputer = SimpleImputer(strategy="median")
X_imputed = imputer.fit_transform(X)

#train/split
X_train, X_valid, y_train_adv, y_valid_adv = train_test_split(
    X_imputed,
    y_adverse,
    test_size=0.2,
    random_state=42
)

_, _, y_train_read, y_valid_read = train_test_split(
    X_imputed,
    y_readmit,
    test_size=0.2,
    random_state=42
)
print("Training rows:", X_train.shape)
print("Validation rows:", X_valid.shape)

#scale features (ensures variables are on same magnitude)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)

#logistic regression baseline
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_scaled, y_train_adv)
pred_log = log_model.predict_proba(X_valid_scaled) [:,1]
auc_log_adv = roc_auc_score(y_valid_adv, pred_log)
print("Logistic Regression Adverse Outcomes AUC:", auc_log_adv)

log_model_read = LogisticRegression(max_iter=1000)
log_model_read.fit(X_train_scaled, y_train_read)
pred_log_read = log_model_read.predict_proba(X_valid_scaled) [:,1]
auc_log_read = roc_auc_score(y_valid_read, pred_log_read)
print("Logistic Regression Readmission AUC:", auc_log_read)

#example prediction
results_preview = pd.DataFrame({"Actual": y_valid_adv.iloc[:10], "Predicted Probability": pred_log[:10]})
print(results_preview)

"""AUC tells us how well the model can distinguish between patients with adverse outcomes vs. without. Closer to 1 = better classification, closer to 0.5 = random guessing."""

#regularized logistic regression
ridge_model = LogisticRegression(penalty='l2', C=0.5, max_iter=1000)
ridge_model.fit(X_train_scaled, y_train_adv)
pred_ridge = ridge_model.predict_proba(X_valid_scaled) [:,1]
auc_ridge_adv = roc_auc_score(y_valid_adv, pred_ridge)
print("Ridge Regression Adverse Outcomes AUC:", auc_ridge_adv)

ridge_model_read = LogisticRegression(penalty='l2', C=0.5, max_iter=1000)
ridge_model_read.fit(X_train_scaled, y_train_read)
pred_ridge_read = ridge_model_read.predict_proba(X_valid_scaled) [:,1]
auc_ridge_read = roc_auc_score(y_valid_read, pred_ridge_read)
print("Ridge Regression  Readmission AUC:", auc_ridge_read)

#random forest model
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)
rf_model.fit(X_train, y_train_adv)
pred_rf = rf_model.predict_proba(X_valid) [:,1]
auc_rf_adv = roc_auc_score(y_valid_adv, pred_log)
print("Random Forest Adverse Outcomes AUC:", auc_rf_adv)

rf_model_read = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)
rf_model_read.fit(X_train, y_train_read)
pred_rf_read = rf_model_read.predict_proba(X_valid) [:,1]
auc_rf_read = roc_auc_score(y_valid_read, pred_rf_read)
print("Random Forest Readmission AUC:", auc_rf_read)

#gradient boosting - lightGBM model (adverse outcome)
model_adv = lgb.LGBMClassifier(n_estimators=300, learning_rate=0.05, max_depth=8, random_state=42)
model_adv.fit(X_train, y_train_adv)
pred_adv = model_adv.predict_proba(X_valid) [:,1]
auc_lgb_adv = roc_auc_score(y_valid_adv, pred_lgb)
print("Adverse Outcome AUC:", auc_lgb_adv)

#same for readmission
model_read = lgb.LGBMClassifier(n_estimators=300, learning_rate=0.05, max_depth=8, random_state=42)
model_read.fit(X_train, y_train_read)
pred_read = model_read.predict_proba(X_valid) [:,1]
auc_lgb_read = roc_auc_score(y_valid_read, pred_read)
print("Readmission AUC:", auc_lgb_read)

#compute macro AUC
macro_log = (auc_lgb_adv + auc_lgb_read) / 2
macro_ridge = (auc_ridge_adv + auc_ridge_read) / 2
macro_rf = (auc_rf_adv + auc_rf_read) / 2
macro_lgb = (auc_lgb_adv + auc_lgb_read) / 2

#compare models
results = pd.DataFrame({
    "Model": ["Logistic Regression", "Regularized Logistic", "Random Forest", "LightGBM"],
    "Adverse Outcome AUC": [auc_log_adv, auc_ridge_adv, auc_rf_adv, auc_lgb_adv],
    "Readmission AUC": [auc_log_read, auc_ridge_read, auc_rf_read, auc_lgb_read],
    "Macro AUC": [macro_log, macro_ridge, macro_rf, macro_lgb]
})
results = results.sort_values(by="Macro AUC", ascending=False)
print(results)

#plot comparison for visual
results.set_index("Model")[["Adverse Outcome AUC", "Readmission AUC", "Macro AUC"]].plot(kind="bar")
plt.title("Model Performance Comparison")
plt.ylabel("AUC Score")
plt.xticks(rotation=45)
plt.show

"""Since Macro AUC is largest with Regularized Logistic Regression, that suggests that overall performance across both tasks is best when using ridge model. So we will use the regularized regression model."""

#ROC curve to visualize
fpr_adv, tpr_adv, _ = roc_curve(y_valid_adv, pred_adv)
fpr_read, tpr_read, _ = roc_curve(y_valid_read, pred_read)
plt.figure()
plt.plot(fpr_adv, tpr_adv, label=f"Adverse Outcome AUC = {auc_ridge_adv:.3f}")
plt.plot(fpr_read, tpr_read, label=f"Readmission AUC = {auc_ridge_read:.3f}")
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve for Both Prediction Tasks")
plt.legend()
plt.show()

importance = pd.DataFrame({"Feature": X.columns, "Importance": model_adv.feature_importances_})
importance = importance.sort_values(by="Importance", ascending=False)
print(importance.head(10))

#train final model on all data
final_adv = lgb.LGBMClassifier(n_estimators=300, learning_rate=0.05, max_depth=8, random_state=42)
final_adv.fit(X_imputed, y_adverse)

final_read = lgb.LGBMClassifier(n_estimators=300, learning_rate=0.05, max_depth=8, random_state=42)
final_read.fit(X_imputed, y_readmit)

#loading test data
test_df = pd.read_csv("test.csv")
test_ids = test_df["encounter_id"]
test_df = test_df.drop(columns=["encounter_id"])

#apply the same preprocessing as before
test_df = pd.get_dummies(test_df)
test_df = test_df.reindex(columns=X.columns, fill_value=0)
test_imputed = imputer.transform(test_df)

#predictions
pred_test_adv = final_adv.predict_proba(test_imputed)[:,1]
pred_test_read = final_read.predict_proba(test_imputed)[:,1]

#create submission
submission = pd.DataFrame({
    "encounter_id":test_ids,
    "adverse_outcome":pred_test_adv,
    "readmission_30d":pred_test_read
})
submission.to_csv("submission.csv",index=False)
print("Submission preview:")
print(submission.head())
print("Submission shape:", submission.shape)

#from google.colab import files
#files.download("submission.csv")